# Site settings
title: "Deep Learning Study"
author: "Scott Lee, Ilheo Jung, Byunghyun Ahn, Kihwan Choi"
description: "This is a blog about deep learning, some mathematics."
keywords: "Software Engineering, Mathematics, Deep Learning, Machine Learning, Statistics, Probability"
biography: ""
colophon: "© DeepStudy - DeepStudy by Scott Lee <br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://DeepStudyAG.github.io"

twitter_username: 
github_username: DeepStudyAG/DeepStudyAG.github.io
linkedin_username: 
facebook_username: 
google-analytics: 

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
